services:
  - type: web
    name: heimdal-webhook
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.app.main:app --reload --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: "10000"
    disk:
      name: data
      mountPath: /data